### PR TITLE
EN-3142: Change SERVICE_MAX_WAIT from 10s to 60s

### PR DESCRIPTION
**Pull request by hatmatter**

### CODE REVIEW

**Comment by RoboticCheese** [comment]
IMO this belongs in a socrata-sensu-server cookbook (or as a configurable attribute upstream). Modifying a fork will make it harder to update our version of the community cookbook in production.

Also, does the block correctly write the file? Last time I used `Chef::Util::FileEdit`, you had to do a `fe.write_file` at the end to flush to disk.

**Comment by hatmatter** [comment]
Yep, I believe I am missing a call to write_file, I'll fix that. My primary reason for placing it into this forked cookbook is that the higher level cookbooks aren't exposed to any of the underlying package details and I decided to keep it that way.

**Comment by RoboticCheese** [comment]
There's also already an attribute for this, it looks like: https://github.com/socrata-cookbooks/sensu-chef/blob/master/templates/default/sensu.default.erb

**Comment by hatmatter** [comment]
Woo hoo!

**Pull request closed without merging**
